### ISSUE TITLE
phrases deleted after clicking "cancel" on "are you sure you want to delete this phrase?"

### ISSUE THREAD

**Issue by ktavakoli** [infinum/phrasing#35]

**Comment by DamirSvrtan** [comment]
Whoopsy daisy :) I've released version 3.2.8 with a fix for this. Thnx for filing this issue.

**Comment by ktavakoli** [comment]
thank you!

also not sure where to send the message as it's not an explicit bug, but
the haml gems that are installed as dependencies caused some issues until i
diverted them with some additional code in my config/application.rb file.
might be useful to include on your wiki post.

(awesome gem in general though!)

On Wed, Jan 7, 2015 at 2:21 PM, DamirSvrtan <notifications@github.com>
wrote:

> Closed #35 <https://github.com/infinum/phrasing/issues/35>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/infinum/phrasing/issues/35#event-215589631>.
>



-- 
Kusha Tavakoli
440.669.4668 | kusha.t@gmail.com

**Comment by DamirSvrtan** [comment]
Can you go into more detail please?

**Comment by ktavakoli** [comment]
Yes. After installing the Phrasing gem, I attempted to use "rails generate
scaffold" and all of the view templates were generated in HAML rather than
ERB.

In order to circumvent this from occurring in the future, I was able to add
the following code to my config/application.rb file inside the Application
class:

    config.generators do |g|
       g.template_engine :erb
    end

Once I did that, I was able to re-run the scaffolds and the views were
generated in ERB again rather than HAML.

Let me know if this helps explain the issue.


On Wed, Jan 7, 2015 at 2:39 PM, DamirSvrtan <notifications@github.com>
wrote:

> Can you go into more detail please?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/infinum/phrasing/issues/35#issuecomment-69105623>.
>



-- 
Kusha Tavakoli
440.669.4668 | kusha.t@gmail.com

**Comment by DamirSvrtan** [comment]
Point well taken, we don't need haml-rails, the standalone haml gem is sufficient for Phrasing. I've pushed v3.2.9 to RubyGems.

**Comment by ktavakoli** [comment]
FYI - I just updated the gem and re-tested and now there is no message before delete. Not a bug if this was intended but wanted to confirm this was the design intent.

**Comment by DamirSvrtan** [comment]
Well, this it seems to vary between Rails versions. On some versions links need only `confirm: 'Are you sure?'` while others need `data: { confirm: 'Are you sure?' }`. I'll check this tomorrow.
