### ISSUE TITLE
Adding new entries after default locale is loaded

### ISSUE THREAD

**Issue by tm1603** [infinum/phrasing#39]
Bug's happening when I18n fallback is set to true with a default_language, and then if the default_language phrases are already loaded into the database, other locale phrases will not be added to database.

My application.rb in config contains:
config.i18n.default_locale = :en
config.i18n.fallbacks = true

For instance (default locale en):
/de/something - imports all DE phrases
/en/something - imports all EN phrases
/hr/something - error

https://cloud.githubusercontent.com/assets/6040256/7495296/599c0478-f40d-11e4-857e-fcd824d66f9a.png
https://cloud.githubusercontent.com/assets/6040256/7495297/59a191ae-f40d-11e4-9739-506c8a90c069.png
https://cloud.githubusercontent.com/assets/6040256/7495298/59c33534-f40d-11e4-8315-ce23df491f4b.png
https://cloud.githubusercontent.com/assets/6040256/7495299/59c38a70-f40d-11e4-8ef6-692d1dc5041c.png
https://cloud.githubusercontent.com/assets/6040256/7495300/59cdb0ae-f40d-11e4-8722-7222377ba59f.png

Stef and me (mostly Stef) think that problem is at: 
https://github.com/infinum/phrasing/blob/master/app/models/phrasing_phrase.rb line: 11

**Comment by DamirSvrtan** [comment]
does updating to '4.0.0rc3' solve the problem?

**Comment by tm1603** [comment]
Yes, it does :)

**Comment by DamirSvrtan** [comment]
Great, I'm closing this.
