### ISSUE TITLE
Trouble hooking-up Phrasing Gem to Rails app's authentication system

### ISSUE THREAD

**Issue by CryptoSnippets** [infinum/phrasing#40]
Hi, sorry for the noob question here.  Thank you for this awesome gem!  I think the problem I'm having is my implementation, not the gem itself.

I've setup the Phrasing Gem in my rails app and aside from the authentication it works properly.  But I have to bypass the auth system by logging into my application before adding the following method:

    # app/helpers/phrasing_helper.rb
    
    module PhrasingHelper
    
      def can_edit_phrases?
        current_user.admin?
      end
    
    end

Because if I try load my app and am not already logged in as admin I get this error:

> NoMethodError in StaticPagesController#home undefined method `admin?'
> for nil:NilClass
> 
>  Extracted source (around line #8):
>     def can_edit_phrases?   	current_user.admin?   end
> 
>   # def can_edit_phrases?

It also works normally if I edit the method to say 'true' instead of 'current_user.admin?' but that's obviously not good.

Thanks in advance for any help.

**Comment by DamirSvrtan** [comment]
The reason why this is failing is because you don't have a `current_user` logged in so the method is returning nil.

Try this:

```ruby
current_user && current_user.admin?
```

**Comment by CryptoSnippets** [comment]
Ah, of course!  thank you, Damir!

**Comment by DamirSvrtan** [comment]
No problem :)
