### ISSUE TITLE
How to stop Phrasing from capturing will_paginate gem's labels?

### ISSUE THREAD

**Issue by CryptoSnippets** [infinum/phrasing#41]
Is there a way to prevent Phrasing from capturing [will_pagenate gem](https://github.com/mislav/will_paginate)'s labels?  It keeps adding 
> **Key:**   will_paginate.next_label 	**Value:**   Next →
> **Key:**   will_paginate.previous_label  **Value:**   ← Previous 

Thanks in advance for any help. :)

**Comment by DamirSvrtan** [comment]
In version 3 we monkeypatched I18n and were on purpose storing anything called with t(key) in the phrasing_phrase table. We decided to ditch that behaviour and so we are releasing version 4. Update phrasing up to version 4.0.0rc9 and this will stop to happen.

**Comment by CryptoSnippets** [comment]
lol you're so onto it! :) Thanks Damir!
