### ISSUE TITLE
"You're in production!" warning

### ISSUE THREAD

**Issue by CryptoSnippets** [infinum/phrasing#42]
Hi,  I'm just wondering why the "You're in production!" warning prints when at https://domain.com/phrasing.  Isn't it to be expected people are editing in production mode?

**Comment by DamirSvrtan** [comment]
It's more of a warning to developers when doing stuff such as exporting/importing data from/to production/development. My experience is that clients will edit a phrase inline on the page where the phrase is placed, and that the backend (the part that's on /phrasing) is more for developers, while not so often used by clients.

Do you have a suggestion on how to maybe enhance the UX?

**Comment by CryptoSnippets** [comment]
Thanks for your reply, Damir.  I don't think it needs UX improvement at all.  I was just debugging other issues in rails when I noticed the message.  I'm still very noob to rails, so it made me wonder if I was missing something important. 

I guess a UX "enhancement" could be to change the message from 'alert red' to 'notice blue' maybe.

**Comment by DamirSvrtan** [comment]
At some point we will enhance the look of the backend part of phrasing but i don't believe it will be that soon. Anyways, thanks for your input.
