### ISSUE TITLE
Reverting back to Rails default translations stills query to database instead in yml file

### ISSUE THREAD

**Issue by vinchi777** [infinum/phrasing#44]
Reverting back to Rails default translations still querys to the database through prhasing.

1st step
t('footer.link1')  //gets translation from config/locales

2nd step. change t to phrase
phrase('footer.link1')  //gets translation from db phrasing table

3rd. step. change back to t
t('phrase') //still gets translation from db table, editing the yml file does not change this value

in my logs
```
  PhrasingPhrase Load (1.4ms)  SELECT `phrasing_phrases`.* FROM `phrasing_phrases` WHERE `phrasing_phrases`.`locale` = 'tr' AND `phrasing_phrases`.`key` = 'footer.link_1' LIMIT 1

```

**Comment by DamirSvrtan** [comment]
In version 3 we monkeypatched I18n and were on purpose storing anything called with t(key) in the phrasing_phrase table. We decided to ditch that behaviour and so we are releasing version 4. Update phrasing up to version 4.0.0rc9 and this will stop happening.

**Comment by vinchi777** [comment]
Thanks! really like this plugin. :+1:
