### ISSUE TITLE
Using Phrasing with Nested Attributes

### ISSUE THREAD

**Issue by nickdb93** [infinum/phrasing#46]
How would one go about using phrasing with nested attributes?

Where an app has many elements:

    32 <% @app.elements.each do |element| %>
    33          <tr>
    34                 <td>    
    35                       <%= phrase(@app.element, :name) %>
    36                </td>

This error is generated:

    undefined method `element' for #<App:0x007fd5dc2c6000>
    app/views/apps/show.html.erb:35:in `block in _app_views_apps_show_html_erb___3008268376876323990_70278249316180'
    > app/views/apps/show.html.erb:32:in `_app_views_apps_show_html_erb___3008268376876323990_70278249316180'

    Parameters:
    {"id"=>"2"}

When replacing line 35 with:

     <%= phrase(@element, :name) %>

I get in return:

     undefined method `id' for nil:NilClass

**Comment by nickdb93** [comment]
SOLVED:

Removed the 'at' symbol and referenced 'name' differently. Line 35, corrected, is as follows:

     <%= phrase(element.name) %>

It should be noted that this also works for attributes nested within nested attributes ("attribute-ception").

**Comment by DamirSvrtan** [comment]
Love it when a ticket gets opened and closed while I'm asleep!

—

**Comment by nickdb93** [comment]
Very cool gem guys. I'd really like to integrate it more deeply into my projects.
