### ISSUE TITLE
Phrases on the same page that have the same text change whenever one of them is altered

### ISSUE THREAD

**Issue by nickdb93** [infinum/phrasing#47]
I'm not sure exactly which data you'd find most helpful about this issue. I guess since Phrases are identified by the text that they hold there may not be a very easy way to fix this.

**Comment by DamirSvrtan** [comment]
Are you using the same key with all of them? If you are, than that is the expected behaviour.

**Comment by nickdb93** [comment]
Hey, thanks for the quick reply, Damir. How do I specify a unique key for each phrase? I'm having some issues finding the supporting docs to use this tool. I must be blind or something.

**Comment by DamirSvrtan** [comment]
Hey @nickdb93.

If you have the same phrase twice in your code, like this:
```ruby
= phrasing_phrase('headline')

.....

= phrasing_phrase('headline')
```

once you change one of them inline, the other one will be changed also - because they are pointing at the same database record.

The same goes for a situation where you're using phrasing to modify your 'own' record:

```ruby
= phrasing_phrase(@first_user, :name)

.....

= phrasing_phrase(@first_user, :name)
```

If you alter the users name, it will be altered in the database, and it will be 'altered' in all the places where it's shown.

If you can hand me a snippet of your code to overview what's going on I would probably be able to solve this faster.

**Comment by nickdb93** [comment]
Hi @DamirSvrtan.

I'm afraid they're not the same code at all. Below is the important part of my `show` page. There's a `!` on each line with a phrase on it.

    !  <p><strong>Name:</strong><%= phrase(@app, :name) %></p>
    !  <p><strong>Infivewords:</strong><%= phrase(@app, :infivewords) %></p>
    !  <p><strong>Description:</strong><%= phrase(@app, :description) %></p>

    <div class="media">
	<div class="media-body">
		<table class="table table-hover">

			<thead>
			 <tr>
			   <th>Name</th>
			   <th>Description</th>
         <th>Delete</th>
         <th> </th>
			 </tr>
			</thead>

      <tbody>
        <tr>

        <% @app.elements.each do |element| %>
          <tr>
      !          <td><h2><%= phrase(element.name) %></h2></td>
      !          <td><h2><%= phrase(element.description) %></h2></td>

                <td><b><%= link_to "Remove", [@app, element], method: :delete, confirm: "Are you sure?" %></b></td>
          </tr>
          <% element.features.each do |feature| %>
              <tr>
         !       <td><%= phrase(feature.name) %><br/></td>
         !       <td><%= phrase(feature.description) %></td>
                <td><%= link_to "Delete", [element, feature], method: :delete %></td>
              </tr>
          <% end %>

**Comment by nickdb93** [comment]
Worth noting: This doesn't just happen to me for each item that's listed. For example, I think you might be saying that since multiple `Elements` and `Features` and their respective names and descriptions are listed on one page, each `element.name` might change when only one is changed on the page.

However, assuming the TEXT that was entered into both an `element.name` and a `feature.description` were the exact same, once user changes just one of those phrases, both phrases would be altered after the intended one was saved and the page was refreshed.

**Comment by unixmonkey** [comment]
Looks to me like you should be using:
```ruby
<%= phrase(element, :name) %>
```
and
```ruby
<%= phrase(feature, :name) %>
```
So that the translation is scoped to the record.

**Comment by nickdb93** [comment]
Yes, this fixed it. Thank you.
