### ISSUE TITLE
Display phrasing edit bubble only on certain pages?

### ISSUE THREAD

**Issue by CryptoSnippets** [infinum/phrasing#48]
Hi, is there a way to enable the edit bubble only on pages where there are phrases?

**Comment by CryptoSnippets** [comment]
I figured it out.  I though I'd need to use javascript to conditionally add a css attribute but it's much easier to do in `phrasing_helper.rb` with `current_page?` :)

**Comment by DamirSvrtan** [comment]
I'm not sure what you mean by getting phrasing controllers in the helper.

I've never needed this, but I believe a colleague of mine handled this situation with javascript - just check if there are any elements with the class `phrasable`, and if not, hide the editing bubble.
