### ISSUE TITLE
No styles

### ISSUE THREAD

**Issue by Shoroh** [infinum/phrasing#49]
Good Job!

That's what I was looking so long.
But look at the picture below — looks like styles issue. Everything is good, no one error in Chrome Developer.
<img width="132" alt="screen shot 2015-07-14 at 23 34 35" src="https://cloud.githubusercontent.com/assets/1865984/8717854/4ab2d77c-2bc9-11e5-9854-1dadac7bd4b6.png">
My application.scss:

```scss
@import "plugins/normalize";
@import "plugins/toastr.min";
@import "font-awesome";
@import "bourbon";
@import "base/base";
@import "neat/settings/visual-grid";
@import "neat";

@import "helpers";

@import "jquery.countdown";
@import "social_buttons";
@import "toast";
@import "devise";
@import "modal";
@import "profile";
@import "modules/modules-dir";
@import "phrasing";
```

Styles are present in DOM:

<img width="1163" alt="screen shot 2015-07-16 at 14 48 52" src="https://cloud.githubusercontent.com/assets/1865984/8717928/e4e24fda-2bc9-11e5-8993-fec16d899c50.png">

**Comment by DamirSvrtan** [comment]
We had an issue with using `@import` instead of `require`. Please upgrade to Phrasing `4.0.0rc9` - we fixed it there.

**Comment by Shoroh** [comment]
Yeah, now it's working well, thanks!
