### ISSUE TITLE
Strange behavior on Heroku

### ISSUE THREAD

**Issue by nickdb93** [infinum/phrasing#50]
On my Heroku App, Phrases are always editable, even when "Editing" is switched off. Also, the "Saved" Icon is always Green, and never actually saves the changes. However, when using domain.com/phrasing, I can edit the phrase successfully.

In works like a dream on my local machine, though.

My view: 
`<p><%= phrase ("This is a phrase.") %></p>`

I've installed the gem, required the JS, stylesheets, etc.

Is there some important part I'm missing? Let me know if I'm missing any code that I should post.

**Comment by DamirSvrtan** [comment]
Which version? 

What does your 'can_edit_phrases?' look like?

Did you look at the logs, do the AJAX requests even go to your server?

**Comment by nickdb93** [comment]
I'm away from my desk for a minute but just checked it on my phone and it looks like it was a turbolinks issue. I will confirm when I get back and close the issue if it is resolved.

**Comment by nickdb93** [comment]
It was solved. Phrasing definitely increases page load times, but it works as designed.
