### ISSUE TITLE
Abnormally long initial page load times

### ISSUE THREAD

**Issue by nickdb93** [infinum/phrasing#51]
With only opne phrase on my site's `index` page, the initial pageload takes way too long. Is this a known byproduct of phrasing, or could I be doing something better?

CSS:
      *= require phrasing

JS:
       //= require jquery
       //= require jquery_ujs
       //= require jquery
       //= require jquery.turbolinks
       //= require phrasing
       //= require turbolinks
       //= require bootstrap-sprockets
       //= require_tree .

View:
<head>
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>
            <%= render 'phrasing/initializer' %>
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum scale=1,scalable=no">
</head >

**Comment by DamirSvrtan** [comment]
Have you tried benchmarking your pageload? Try to use the rack-mini-profiler gem to see what takes so long - is it the database, page rendering or something else.

Benchmark your page load with the present phrase and without it.

**Comment by DamirSvrtan** [comment]
Do we have an update on this?

**Comment by nickdb93** [comment]
Honestly I think the only thing we can do is be smart about loading assets. Adding 'async => true' to the loading script in the view and insuring that you load your JS and render The phrasing/init at the END of your body seems to be the only way to handle this. If your root doesn't have any phrases on it, I'd suggest looking into loading the JS for phrasing on only pages that have phrases, and of course caching the JS (done in most browsers by default).

I had been looking into forking Phrasing to create a lighter-weight less feature-rich version, but I simply don't think I have the time or skills.

**Comment by nickdb93** [comment]
After some benchmarking, I concluded that loading the assets is what was slowing down the load times. However, on a fresh project it seems to be a little better (although my server's resources have also increased 16x)

**Comment by DamirSvrtan** [comment]
Okay, so I guess that you've found a solution for this and it doesn't have to do anything with phrasing but with loading of assets.
