### ISSUE TITLE
Phrasing try to load keys, which it should don't care

### ISSUE THREAD

**Issue by VoloshynDmytro** [infinum/phrasing#53]
In my log file one part of load trace looks a bit weird, because at the view file for 'navigation' I don't use phrasing helper, just 't' helper for I18n, for example:
`=  link_to t('navigation.home'), root_path`
`=  link_to t('navigation.boards'), adverts_path`
`=  link_to t('navigation.about_us'), about_us_path`

and in log file I see: 

`PhrasingPhrase Load (0.3ms)  SELECT  "phrasing_phrases".* FROM "phrasing_phrases" WHERE "phrasing_phrases"."locale" = $1 AND "phrasing_phrases"."key" = $2  ORDER BY "phrasing_phrases"."id" ASC LIMIT 1  [["locale", "uk"], ["key", "navigation.home"]]
  PhrasingPhrase Load (0.2ms)  SELECT  "phrasing_phrases".* FROM "phrasing_phrases" WHERE "phrasing_phrases"."locale" = $1 AND "phrasing_phrases"."key" = $2  ORDER BY "phrasing_phrases"."id" ASC LIMIT 1  [["locale", "uk"], ["key", "navigation.boards"]]
  PhrasingPhrase Load (0.3ms)  SELECT  "phrasing_phrases".* FROM "phrasing_phrases" WHERE "phrasing_phrases"."locale" = $1 AND "phrasing_phrases"."key" = $2  ORDER BY "phrasing_phrases"."id" ASC LIMIT 1  [["locale", "uk"], ["key", "navigation.about_us"]]
  PhrasingPhrase Load (0.2ms)  SELECT  "phrasing_phrases".* FROM "phrasing_phrases" WHERE "phrasing_phrases"."locale" = $1 AND "phrasing_phrases"."key" = $2  ORDER BY "phrasing_phrases"."id" ASC LIMIT 1  [["locale", "uk"], ["key", "navigation.career"]]
`
Should it load translations keys, which I don't using via 'phrase' helper but just with 't' ?  it's slowing down page loading

**Comment by DamirSvrtan** [comment]
In version 3 we monkeypatched I18n and were on purpose storing anything called with t(key) in the phrasing_phrase table. We decided to ditch that behaviour and so we are releasing version 4. Update phrasing up to version 4.0.0rc10 and this will stop happening.
