### ISSUE TITLE
problem with  activerecord-sqlserver-adapter (4.2.3)

### ISSUE THREAD

**Issue by paulewetzel** [infinum/phrasing#54]
I am using  activerecord-sqlserver-adapter (4.2.3)  against a legacy database. When I edit an individual phrase(@model, :prop), it works fine for me.  But when I click the edit-all button, I get this error:

   PhrasingPhrase Load (1.7ms)  EXEC sp_executesql N'SELECT [phrasing_phrases].* FROM [phrasing_phrases] WHERE [phrasing_phrases].[locale] = ''en'' AND (value is not null)  ORDER BY phrasing_phrases.key'
TinyTds::Error: Incorrect syntax near the keyword 'key'.: EXEC sp_executesql N'SELECT [phrasing_phrases].* FROM [phrasing_phrases] WHERE [phrasing_phrases].[locale]'SELECT [phrasing_phrases].* FROM [phrasing_phrases] WHERE [phrasing_phrases].[locale] = ''en'' AND (value is not null)  ORDER BY phrasing_phrases.key' AND (value is not null)  ORDER BY phrasing_phrases.key'
Completed 500 Internal Server Error in 3ms

TinyTds::Error - Incorrect syntax near the keyword 'key'.: activerecord-sqlserver-adapter (4.2.3) lib/active_record/connection_adapters/sqlserver/database_statements.rb:336:in `handle_to_names_and_values_dblib'

The SQL is coming out a malformed, this [phrasing_phrases].[locale] = ''en'', should be [phrasing_phrases].[locale] = 'en' . When I look at what rails logs in the terminal window,  it looks like ' 'en' ' , 2 single quotes on wither side of the "en" value. 

Also, the order by clause , "ORDER BY phrasing_phrases.key",  which is causing the current error, also raises an error when run in an Sql Manager query window. Changing the order by clause to "phrasing_phrases.[key]" eliminates the error in the sql manage window.

**Comment by DamirSvrtan** [comment]
Do you know how to fix this issue in the gem? I would like to add postgres, mysql and sqlite to the test cases for Travis-CI and when you make a change, i'd like to see if they pass. Unfortunately Travis-CI doesn't have an integration with sqlserver but if the tests pass on those three databases, I'm okay with trusting you that they're passing just as well on sqlserver :)

**Comment by paulewetzel** [comment]
I will look into it tonight. I thought you guys were using Semaphore based on one of your articles.  Thanks for the quick response.

**Comment by paulewetzel** [comment]
Ends up that all I had to do to get it working was change 
query.order("#{query.table_name}.key")  
to 
query = query.order("#{query.table_name}.[key]")  in  PhrasingPhrasesController#index 

Do you know of any db's that you support that do not support bracketed field names by chance?

**Comment by DamirSvrtan** [comment]
Merged in https://github.com/infinum/phrasing/pull/55
