### ISSUE TITLE
Automatically imports other gems translations?

### ISSUE THREAD

**Issue by jasonyost** [infinum/phrasing#59]
I am using phrasing in addition to a few other gems with create pages and have translations available. When I visit the path to a page generated by another gem, anything which is translatable in that gem is dumped into the phrases DB.

For example with the rails_admin gem, any time the dashboard is visited all of the labels are added to the phrases DB.

Is there a way around this?
![phrasing-unintended-keys](https://cloud.githubusercontent.com/assets/331400/12666549/3c7f5b78-c5ff-11e5-9e04-146cb1ad6d5c.png)

**Comment by DamirSvrtan** [comment]
Hey, please upgrade to [4.0.0rc12](https://rubygems.org/gems/phrasing), we kicked out that behaviour in version 4.
