### ISSUE TITLE
Add better css to the tooltip.

### ISSUE THREAD

**Issue by iruzevic** [infinum/phrasing#69]
Add better styling to the tooltip.

Currently you can override the tooltip style accidentally with projects style.
I suggest adding bem methodology and introducing !important overrides

Check the image:
![screen shot 2017-07-18 at 11 44 53](https://user-images.githubusercontent.com/23283324/28311002-8a73cd5e-6bae-11e7-9355-9c4cbbacb3b2.png)

**Comment by cilim** [comment]
This is also fixed in the newer versions.

Please update to `'~> 4.2.0'`
