### ISSUE TITLE
Chrome flickering and reloading page when moving back and forward

### ISSUE THREAD

**Issue by thebigstack** [infinum/phrasing#71]
We are using Phrasing on a small app we are developing. It is working well however for some reason whenever we click a link when logged in as admin or move back or forwards, the page flickers for a while before settling. 

Any ideas how to solve this? 

Thanks!

**Comment by cilim** [comment]
This gem doesn't have any dependencies that would cause such behaviour.

It is probably an issue in your JS files that causes this behaviour.
