### ISSUE TITLE
JS problems on iOS Safari

### ISSUE THREAD

**Issue by tomislav-s** [infinum/phrasing#72]
It seems that phrasing is breaking my JS on load as admin on iOS version 9.3.4 Safari.

The error at hand seems to be:

`QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
setItem — phrasing.self-ef6f808779f443cb83ac8cc7280d2d3f6f2a97c9043a08645491254e8f7b6992.js:61
(anonymous function) — phrasing.self-ef6f808779f443cb83ac8cc7280d2d3f6f2a97c9043a08645491254e8f7b6992.js:61
dispatch — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:4671
handle — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:4339
trigger — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:4580
(anonymous function) — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:5290
each — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:385
each — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:137
trigger — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:5289
(anonymous function) — phrasing.self-ef6f808779f443cb83ac8cc7280d2d3f6f2a97c9043a08645491254e8f7b6992.js:24
dispatch — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:4671
handle — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:4339
trigger — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:4580
(anonymous function) — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:5290
each — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:385
each — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:137
trigger — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:5289
(anonymous function) — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:8482
phrasing_setup — phrasing.self-ef6f808779f443cb83ac8cc7280d2d3f6f2a97c9043a08645491254e8f7b6992.js:147
fire — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:3149
fireWith — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:3261
ready — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:3473
completed — jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js:3504
`

on

`Phrasing.Bus.on('phrasing:edit-mode:off', function(){
    $('.phrasable').removeClass("phrasable-on").attr("contenteditable", "false");
    localStorage.setItem(Phrasing.EDIT_MODE_KEY, "false");
  });`

**Comment by cilim** [comment]
The problem is that private mode is probably enabled, which disables storing anything to `localStorage`. Since a disabled `localStorage` can cause issues on the application level, it makes sense to handle this case there, and not the gem level.
