### ISSUE TITLE
Error: Missing partial phrasing/_initializer

### ISSUE THREAD

**Issue by Raycoms** [infinum/phrasing#75]
method=GET path=/faq format=html controller=FaqController action=faq status=500 error='ActionView::Template::Error: Missing partial phrasing/_initializer with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :arb, :jbuilder]}. Searched in:
  * "/home/ray/IdeaProjects/MinnowBooster/app/views"
  * "/home/ray/.gems/gems/phrasing-2.1.3/app/views"
  * "/home/ray/.gems/bundler/gems/activeadmin-7848a53ffae2/app/views"
  * "/home/ray/.gems/gems/kaminari-core-1.1.1/app/views"
  * "/home/ray/.gems/gems/devise-4.3.0/app/views"
' duration=29.52 view=0.00 db=0.79

When I put this in my application.html.erb

  <%= render 'phrasing/initializer'%>

**Comment by gustavoelizalde** [comment]
@Raycoms I'm getting the same error. Have you found a solution?

**Comment by Raycoms** [comment]
Updating to a newer version of infinum seemed to had fixed it.

**Comment by gustavoelizalde** [comment]
@Raycoms my `gem "phrasing" ` line installed this version on Gemfile.lock

phrasing (2.1.3)

Which version are you using?

**Comment by Raycoms** [comment]
# Gem for web-editor
gem "phrasing", '>= 4.0.0rc16'

2018-01-04 22:40 GMT+00:00 Gustavo Sebastian Elizalde Ibañez <
notifications@github.com>:

**Comment by gustavoelizalde** [comment]
@Raycoms thanks a LOT man, I'll test this version now.

**Comment by cilim** [comment]
Hey everyone, the gem had this issue in the previous versions (2.1.3 and below).

To fix it, please update phrasing gem to `>= 4.0.0`
