### ISSUE TITLE
Where to include 'phrasing/initializer' partial?

### ISSUE THREAD

**Issue by vfonic** [infinum/phrasing#78]
The documentation says: 
> Include the phrasing html initializer at the top of your application layout file.

Which is not very specific. The top of application layout file is `<!DOCTYPE html>`, not `<body>`, where I saw the partial being added in the dummy app.

Would it be more correct to say that it needs to be added right below the opening `<body>` tag?

Also, the example syntax shows haml syntax and I think majority of people use erb, so maybe it would be better to have the good ol' erb syntax instead:
`<%= render 'phrasing/initializer' %>`

**Comment by cilim** [comment]
I agree. The documentation is a bit misleading. I will change the readme as suggested.

Thank you for helping out.
