### ISSUE TITLE
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

### ISSUE THREAD

**Issue by ACPK** [infinum/phrasing#79]
% rake db:migrate
      rake aborted!
      StandardError: An error has occurred, this and all later migrations canceled:

      Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

        class CreatePhrasingPhrases < ActiveRecord::Migration[4.2]
      db/migrate/20180327015847_create_phrasing_phrases.rb:1:in `<top (required)>'

      Caused by:
      StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

        class CreatePhrasingPhrases < ActiveRecord::Migration[4.2]
      db/migrate/20180327015847_create_phrasing_phrases.rb:1:in `<top (required)>'
      Tasks: TOP => db:migrate

**Comment by cilim** [comment]
Confirming. This is a bug that came with newer versions of Rails.
I will reference this issue once it's fixed in a commit.
