### ISSUE TITLE
"Edit All" goes to a 404 page

### ISSUE THREAD

**Issue by ACPK** [infinum/phrasing#81]
When an admin clicks "edit all", it redirects to /phrasing.

However, the gem doesn't seem to create a phrasing route.

**Comment by cilim** [comment]
@ACPK the gem does create a `/phrasing` route. You can see the implementation [here](https://github.com/infinum/phrasing/blob/master/config/routes.rb).

You also need to make sure to do all the necessary steps in the `Installation` and `Setup` documented in the [README.md file](https://github.com/infinum/phrasing/blob/master/README.md)

If you need any help, reopen the issue please.
