### ISSUE TITLE
Phrasing javascript inteference

### ISSUE THREAD

**Issue by bestdramana** [infinum/phrasing#85]
I've got an app with RoR, jquery and materializecss, since i've added phrasing, funky things started happening with my modals and ajax call and i keep having this error 
```
editor.self-398dc420614065b790524c83117b2f8bfe140694ac0d46f17bb16e8576612af0.js?body=1:99 Uncaught TypeError: Cannot read property 'classList' of null
    at checkTextHighlighting (editor.self-398dc420614065b790524c83117b2f8bfe140694ac0d46f17bb16e8576612af0.js?body=1:99)
    at editor.self-398dc420614065b790524c83117b2f8bfe140694ac0d46f17bb16e8576612af0.js?body=1:36
```

To give some context, it's quite simple, i open my modal, fill out the form, click my anchor bind to a jquery on click event that has an ajax call but then the error happen. Did someone had similar issue ?

**Comment by cilim** [comment]
Hi @bestdramana

this could be quite difficult to debug for us cause it's such a specific case...

You might be fetching the `classList` of an element dependent on the DOM positioning, for example next or siblings etc...and phrasing is changing the HTML structure so it cannot find the necessary element...

You can try and test this behaviour in 2 cases:
1. Logged in
2. Logged out

Is the error occurring in both scenarios?

**Comment by bestdramana** [comment]
Hi ! I debugged the `editor.js`file and find out what cause the problem. it's on the `onmouseclick` event i had an anchor that some JS in the app was changing the DOM dynamically so my anchor was loosing the `phrasing` span parent. Just weird that in that case phrasing was still trying to get the parentNode

**Comment by cilim** [comment]
I'll close this issue and if there's any need in the future and it becomes more frequent, we'll think of a solution.
