### ISSUE TITLE
What's new in v4.3.0?

### ISSUE THREAD

**Issue by vfonic** [infinum/phrasing#88]
I just saw you released new version of the gem, but can't find anything in the CHANGELOG.

Anything new in the last version? 

Thanks!
Viktor

**Comment by cilim** [comment]
Here you go :)

```
## 4.3.0 (June 13th, 2019)

 - Add support for Rails 6
 - Remove jquery.turbolinks fix suggestion
```

reference: https://github.com/infinum/phrasing/compare/v4.3.0...master

**Comment by vfonic** [comment]
Thanks for the quick response!
