### ISSUE TITLE
Utilizing ActionText for rich text phrases

### ISSUE THREAD

**Issue by neiljohari** [infinum/phrasing#89]
Hello! I'm not sure this is exactly relevant to what phrasing tries to accomplish, but I think taking advantage of ActionText for Rails 6 might be an interesting way to use phrasing as a lightweight CMS where applicable.

**Comment by cilim** [comment]
@neiljohari your suggestion has great potential but currently, we are not focused on extending Phrasing to have a CMS-like behavior.
If you are up to a challenge, we would love to see your PR.

**Comment by vr4b4c** [comment]
Hi @neiljohari @cilim 

I'm closing this issue because it's been inactive for a few months, and no one is working actively to support it.

Please feel free to reopen once you are ready to take action (introduce it as a new feature) or contribute directly.
