### ISSUE TITLE
Prevent saving automatically when "edit" is not enabled

### ISSUE THREAD

**Issue by MaikelGG** [infinum/phrasing#91]
We are using phrasing on a multilingual website. One our users automatically translated webpages in other languages. But when he is logged in as editor he automatically translates all strings (using built-in translation in chrome) on that page and this is stored in the table, while editing is not enabled. It seems the "edit mode" only applies to the front end, but can there also be put in place a check to prevent storing it in the database when editing is not enabled?

**Comment by cilim** [comment]
Very interesting scenario you got there @MaikelGG :)

I'll checkout the code sometime this week. Once I have more info, I'll get back to you, but I believe we'll have to patch this up for sure.

**Comment by cilim** [comment]
@MaikelGG version [4.3.2](https://rubygems.org/gems/phrasing/versions/4.3.2) has been released.

Thanks again for the issue report!

**Comment by MaikelGG** [comment]
Thank you for your efforts!
