### ISSUE TITLE
Update CHANGELOG.md template

### ISSUE THREAD

**Issue by nikajukic** [infinum/phrasing#94]
Please use the latest version of [Infinum's default changelog template](https://github.com/infinum/default_rails_template/blob/master/GEM_CHANGELOG_TEMPLATE.md) and rename it to CHANGELOG.md:

# Changelog

## [v1.0.0](https://github.com/infinum/some-gem/tree/v-current) (YYYY-MM-DD)
[Full Changelog](https://github.com/infinum/some-gem/compare/v-previous...v-current)

### Enhancements

- Added something [\#52](https://github.com/link-to-pr-or-issue)

### Bugfixes

- Fixed something [\#52](https://github.com/link-to-pr-or-issue)

### Breaking changes / Deprecations

- Changed something [\#52](https://github.com/link-to-pr-or-issue)

**Comment by cilim** [comment]
@nika I adapted the changelog according to our template: https://github.com/infinum/phrasing/pull/95

**Comment by nikajukic** [comment]
Great, thanks!
